### ISSUE TITLE
Does this plugin work with Webpack 4?

### ISSUE THREAD

**Issue by bummzack** [leviwheatcroft/metalsmith-webpack-2#2]
I'm using Webpack 4, running it on its own works well, but when invoked via the metalsmith-webpack-2 plugin, I get no generated output. There are no errors either.

**Comment by leviwheatcroft** [comment]
No, only webpack 2 sorry.

I don't have much motivation to update it, I came to the conclusion a long while back that you're better off building your assets for metalsmith in a separate process, rather than trying to shoe-horn webpack into a plugin.

**Comment by bummzack** [comment]
I see. Thanks for your reply!
